version: '3.4'

services:
  marsrover.api:
    image: ${DOCKER_REGISTRY-}marsroverapi
    build:
      context: .
      dockerfile: src/MarsRover.Api/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ConnectionString=Server=sqlserver;Initial Catalog=MarsRover;User Id=sa;Password=P@ssWord123!
    depends_on:
      - sqlserver

  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "P@ssWord123!"
      ACCEPT_EULA: "Y"
    ports:
      - "4444:1433"

